const images = {
  logo: '/assets/images/landing-page/logo.svg',
  heroBackground:'/assets/images/landing-page/wave.svg',
  heroImage:'/assets/images/landing-page/hero_image.svg',
  commitmentIcon:'/assets/images/landing-page/commitment_icon.svg',
  excellenceIcon:'/assets/images/landing-page/excellence_icon.svg',
  integrityIcon:'/assets/images/landing-page/integrity_icon.svg',
  respectIcon:'/assets/images/landing-page/respect_icon.svg',
  happyNurseandManWheelchair:'/assets/images/landing-page/happy-nurse-man-wheelchair.svg',
  ladiesDonating:'/assets/images/landing-page/ladies_donating.svg',
  ladyandLadyWheelchair:'/assets/images/landing-page/lady_lady_wheelchair.svg',
  manDrinkCoffee:'/assets/images/landing-page/man-drink-coffee.svg',
  prayingMan:'/assets/images/landing-page/man-praying.svg',
  nurseCheckingMan:'/assets/images/landing-page/nurse-checking-man.svg',
  nurseSittingWithOldManWoman:'/assets/images/landing-page/nurse-old-man-woman-sofa.svg',
  oldageHome:'/assets/images/landing-page/oldagehome.svg',
  oldManWithCaretaker:'/assets/images/landing-page/oldman_caretaker.svg',
  patientWithDoctor:'/assets/images/landing-page/patient-with-kind-doctor.svg',
  socialworkers:'/assets/images/landing-page/socialworkers-helping-disabled-man.svg',
  womanCaregiver:'/assets/images/landing-page/woman_caregiver_outdoor.svg',
  doctorCaringWoman:'/assets/images/landing-page/doctor-taking-care-senior-woman.svg',
  seniorWomanSittingBedroom:'/assets/images/landing-page/senior-woman-sitting-bedroom.svg',
  joyfulOldLady:'/assets/images/landing-page/joyful-old-lady-sitting-couch.svg',
  ladyDoctor1:'/assets/images/landing-page/lady_doctor_1.svg',
  ladyDoctor2:'/assets/images/landing-page/lady_doctor_2.svg',
  maleDoctor1:'/assets/images/landing-page/male_doctor_1.svg',
  holdingHands:'/assets/images/landing-page/holding_hands.svg',
  staffs1:'/assets/images/landing-page/staffs1.svg',
  staffs2:'/assets/images/landing-page/staffs2.svg',
  ladyDoctorRaindrop:'/assets/images/landing-page/lady_doctor_raindrop.svg',
  womenInWheelchair:'/assets/images/landing-page/womenInWheelchair.svg',
  logoutIcon:'/assets/images/logout_icon.svg',
  manLogin:'/assets/images/landing-page/man_login.svg',
  seniorsEatingDinner:'/assets/images/landing-page/Sr_men_women_eating_dinner.svg',
  seniorsWatchingTV:'/assets/images/landing-page/senior_people_watching_tv.svg',
  seniorsPlayingChess:'/assets/images/landing-page/senior_people_playing_chess.svg',
  DrCheckingSrWomen:'/assets/images/landing-page/DrCheckingSrWomen.svg',
  maleHealthVisitor:'/assets/images/landing-page/male_health_visitor.svg',
  gatheringSrPeople:'/assets/images/landing-page/gathering_senior_people.svg',
  femaleHealthVisitor:'/assets/images/landing-page/female-nurse-taking-care-elderly-person.svg',
  nurseFeedingSrMan:'/assets/images/landing-page/nurse_feeding_Sr_man.svg',
  oldmanReadingBook:'/assets/images/landing-page/oldman_reading_book.svg',
  DrOldWoman1:'/assets/images/landing-page/doctor_old_woman1.svg',
  DrOldWoman2:'/assets/images/landing-page/doctor_old_woman2.svg',
  DrOldWoman3:'/assets/images/landing-page/doctor_old_woman3.svg',
  DrOldWoman4:'/assets/images/landing-page/doctor_old_woman4.svg',
  DrOldWoman5:'/assets/images/landing-page/doctor_old_woman5.svg',
  DrOldMan:'/assets/images/landing-page/doctor_and_old_man.svg',
  DrGivingPills:'/assets/images/landing-page/doctor_giving_pills.svg',
  alexander:'/assets/images/landing-page/alexandar.svg',
  abraham:'/assets/images/landing-page/abraham.svg',
  melissa:'/assets/images/landing-page/melissa.svg',
  chapelIcon:'/assets/images/landing-page/chapel_icon.svg',
  foodIcon:'/assets/images/landing-page/food_icon.svg',
  geriatricsIcon:'/assets/images/landing-page/geriatrics_icon.svg',
  handShaking:'/assets/images/landing-page/hand_shaking.svg',
  seniorsSelfie:'/assets/images/landing-page/seniorsSelfie.svg',






  // Add more image constants as needed
};

export default images;
